# PHP
phpfpm:
  restart: always
  extends:
    file: php-fpm-7.yml
    service: phpfpm
  links:
    - db:db
  volumes:
    - ./php-fpm-7/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./php-fpm-7/php.ini:/usr/local/etc/php/php.ini
    - ../application:/var/www/application
    - ./log/php-fpm:/var/log/php-fpm

# NGINX
nginx:
  restart: always
  image: nginx
  ports:
    - "8000:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./log/nginx:/var/log/nginx
    - ../application:/var/www/application


# MYSQL
db:
    restart: always
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ../application/database/migrations/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root

#  restart: always
#  image: mysql
#
#  environment:
#    MYSQL_ROOT_PASSWORD: 123456
#    MYSQL_USER: user
#    MYSQL_PASSWORD: password
#    MYSQL_DATABASE: database
#  volumes:
##    - ./mysql/databases:/var/lib/mysql
#    - ./log/mysql:/var/log/mysql

#  - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
